# Generated by Django 3.2.4 on 2021-06-12 02:19

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210610_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=account.models.uploadProfileImage),
        ),
    ]
